'use client'

import { useState, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Search, Sparkles, Download, Tag, TrendingUp, Hash, Copy, Check } from 'lucide-react'
import { GlassCard } from '@/components/ui/GlassCard'
import { CopyButton } from '@/components/ui/CopyButton'
import { cn, copyToClipboard } from '@/lib/utils'

// ── Keyword Engine ─────────────────────────────────────────

const INTENT_MODIFIERS = {
  informational: ['what is', 'how to', 'guide to', 'best way to', 'tips for', 'learn', 'understanding', 'explained', 'tutorial', 'examples of'],
  commercial: ['best', 'top', 'review', 'vs', 'compare', 'alternatives to', 'cheap', 'affordable', 'premium', 'recommended'],
  transactional: ['buy', 'get', 'download', 'free', 'discount', 'deal', 'price', 'cost', 'order', 'hire'],
  navigational: ['tool', 'online', 'app', 'website', 'platform', 'software', 'service', 'site'],
}

const LONG_TAIL_SUFFIXES = [
  'for beginners', 'for small business', 'for students', 'for professionals',
  'without experience', 'in 2025', 'step by step', 'complete guide',
  'that works', 'tips and tricks', 'made easy', 'from scratch',
  'best practices', 'common mistakes', 'checklist', 'template',
]

const QUESTION_PREFIXES = ['how to', 'what is', 'why is', 'when to', 'where to', 'which', 'who uses', 'can i']

function generateKeywords(seed: string, niche: string, lang: string) {
  if (!seed.trim()) return { keywords: [], questions: [], lsi: [] }

  const s = seed.toLowerCase().trim()
  const n = niche.toLowerCase().trim()
  const context = n ? `${s} ${n}` : s

  // Base keyword variations
  const keywords: { kw: string; intent: string; difficulty: string; volume: string }[] = []

  // Add seed itself
  keywords.push({ kw: s, intent: 'mixed', difficulty: 'High', volume: '10K–100K' })

  // Intent-based
  Object.entries(INTENT_MODIFIERS).forEach(([intent, mods]) => {
    mods.slice(0, 3).forEach(mod => {
      keywords.push({
        kw: `${mod} ${context}`.trim(),
        intent,
        difficulty: intent === 'transactional' ? 'High' : intent === 'commercial' ? 'Medium' : 'Low',
        volume: intent === 'informational' ? '1K–10K' : '100–1K',
      })
    })
  })

  // Long-tail
  LONG_TAIL_SUFFIXES.slice(0, 6).forEach(suf => {
    keywords.push({
      kw: `${context} ${suf}`.trim(),
      intent: 'informational',
      difficulty: 'Low',
      volume: '100–1K',
    })
  })

  // Questions
  const questions = QUESTION_PREFIXES.map(q => ({
    q: `${q} ${context}?`,
    type: 'PAA' as const,
  }))

  // LSI (Latent Semantic Indexing) - related terms
  const words = s.split(' ')
  const lsi = [
    ...words.map(w => `${w} tips`),
    ...words.map(w => `${w} guide`),
    `${s} examples`,
    `${s} vs`,
    `${s} benefits`,
    `${s} tools`,
    `free ${s}`,
    `online ${s}`,
    `${s} software`,
    `${s} platform`,
  ].filter(Boolean)

  return { keywords: keywords.slice(0, 24), questions, lsi: Array.from(new Set(lsi)).slice(0, 16) }
}

const INTENT_CONFIG: Record<string, { color: string; bg: string; label: string }> = {
  informational: { color: '#3b82f6', bg: '#3b82f618', label: 'Info' },
  commercial:    { color: '#f59e0b', bg: '#f59e0b18', label: 'Commercial' },
  transactional: { color: '#22c55e', bg: '#22c55e18', label: 'Buy' },
  navigational:  { color: '#8b5cf6', bg: '#8b5cf618', label: 'Nav' },
  mixed:         { color: '#6366f1', bg: '#6366f118', label: 'Mixed' },
}

const DIFFICULTY_COLOR: Record<string, string> = {
  Low: '#22c55e', Medium: '#f59e0b', High: '#ef4444',
}

// ── Component ──────────────────────────────────────────────

export function KeywordGeneratorTool() {
  const [seed, setSeed] = useState('')
  const [niche, setNiche] = useState('')
  const [activeTab, setActiveTab] = useState<'keywords' | 'questions' | 'lsi'>('keywords')
  const [generated, setGenerated] = useState<ReturnType<typeof generateKeywords> | null>(null)
  const [copiedKw, setCopiedKw] = useState<string | null>(null)

  const handleGenerate = () => {
    if (!seed.trim()) return
    setGenerated(generateKeywords(seed, niche, 'en'))
  }

  const copyKw = async (kw: string) => {
    await copyToClipboard(kw)
    setCopiedKw(kw)
    setTimeout(() => setCopiedKw(null), 1500)
  }

  const exportAll = () => {
    if (!generated) return
    const lines = [
      '# Keywords Generated by Toolify',
      `# Seed: ${seed}`,
      `# Generated: ${new Date().toLocaleString()}`,
      '',
      '## Main Keywords',
      ...generated.keywords.map(k => `${k.kw} | ${k.intent} | ${k.difficulty} | ${k.volume}`),
      '',
      '## Questions (People Also Ask)',
      ...generated.questions.map(q => q.q),
      '',
      '## LSI Keywords',
      ...generated.lsi,
    ].join('\n')
    const blob = new Blob([lines], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `keywords-${seed.replace(/\s+/g, '-')}.txt`; a.click()
    URL.revokeObjectURL(url)
  }

  const copyAll = () => {
    if (!generated) return
    const all = [...generated.keywords.map(k => k.kw), ...generated.questions.map(q => q.q), ...generated.lsi].join('\n')
    copyToClipboard(all)
  }

  const TABS = [
    { id: 'keywords' as const, label: 'Keywords', count: generated?.keywords.length, icon: Tag },
    { id: 'questions' as const, label: 'Questions', count: generated?.questions.length, icon: Search },
    { id: 'lsi' as const, label: 'LSI Terms', count: generated?.lsi.length, icon: Hash },
  ]

  return (
    <div className="space-y-5">
      {/* Input */}
      <GlassCard hover={false}>
        <h3 className="font-semibold mb-4 flex items-center gap-2">
          <Sparkles size={15} className="text-primary" />
          Generate Keywords
        </h3>
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium mb-2 text-muted-foreground">
              Seed Keyword / Topic *
            </label>
            <div className="relative">
              <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
              <input
                type="text"
                value={seed}
                onChange={e => setSeed(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleGenerate()}
                placeholder="e.g. email marketing, react hooks, weight loss"
                className="w-full pl-9 pr-4 py-3 rounded-xl bg-secondary/50 border border-border focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all text-sm"
              />
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium mb-2 text-muted-foreground">
              Niche / Industry (optional)
            </label>
            <input
              type="text"
              value={niche}
              onChange={e => setNiche(e.target.value)}
              placeholder="e.g. SaaS, fitness, cooking, B2B"
              className="w-full px-4 py-3 rounded-xl bg-secondary/50 border border-border focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all text-sm"
            />
          </div>
          <button
            onClick={handleGenerate}
            disabled={!seed.trim()}
            className="w-full py-3 rounded-xl bg-primary text-primary-foreground font-semibold text-sm hover:opacity-90 transition-all disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-glow-brand"
          >
            <Sparkles size={16} />
            Generate Keywords
          </button>
        </div>
      </GlassCard>

      {/* Results */}
      <AnimatePresence>
        {generated && (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            {/* Stats bar */}
            <div className="grid grid-cols-3 gap-3">
              {[
                { label: 'Keywords', value: generated.keywords.length, color: '#6366f1', icon: Tag },
                { label: 'Questions', value: generated.questions.length, color: '#3b82f6', icon: Search },
                { label: 'LSI Terms', value: generated.lsi.length, color: '#10b981', icon: Hash },
              ].map(s => {
                const Icon = s.icon
                return (
                  <div key={s.label} className="glass-card p-3 text-center">
                    <Icon size={14} className="mx-auto mb-1.5" style={{ color: s.color }} />
                    <div className="text-xl font-bold font-display" style={{ color: s.color }}>{s.value}</div>
                    <div className="text-xs text-muted-foreground">{s.label}</div>
                  </div>
                )
              })}
            </div>

            {/* Tab bar */}
            <GlassCard hover={false} className="p-0 overflow-hidden">
              <div className="flex border-b border-border">
                {TABS.map(tab => {
                  const Icon = tab.icon
                  return (
                    <button
                      key={tab.id}
                      onClick={() => setActiveTab(tab.id)}
                      className={cn(
                        'flex-1 flex items-center justify-center gap-1.5 py-3 text-sm font-medium transition-all',
                        activeTab === tab.id
                          ? 'text-primary border-b-2 border-primary bg-primary/5'
                          : 'text-muted-foreground hover:text-foreground'
                      )}
                    >
                      <Icon size={13} />
                      {tab.label}
                      {tab.count && (
                        <span className="text-xs px-1.5 py-0.5 rounded-full bg-secondary font-medium">{tab.count}</span>
                      )}
                    </button>
                  )
                })}
              </div>

              <div className="p-4">
                {/* Keywords tab */}
                {activeTab === 'keywords' && (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-2">
                    {/* Legend */}
                    <div className="flex flex-wrap gap-2 mb-3">
                      {Object.entries(INTENT_CONFIG).map(([k, v]) => (
                        <span key={k} className="text-[11px] px-2 py-0.5 rounded-full font-medium" style={{ background: v.bg, color: v.color }}>
                          {v.label}
                        </span>
                      ))}
                    </div>
                    {generated.keywords.map((kw, i) => {
                      const ic = INTENT_CONFIG[kw.intent] || INTENT_CONFIG.mixed
                      return (
                        <motion.div
                          key={kw.kw}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.02 }}
                          className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-secondary/50 group transition-colors"
                        >
                          <span className="text-xs text-muted-foreground w-5 text-right shrink-0">{i + 1}</span>
                          <span className="flex-1 text-sm font-medium">{kw.kw}</span>
                          <span className="text-[11px] px-2 py-0.5 rounded-full shrink-0" style={{ background: ic.bg, color: ic.color }}>{ic.label}</span>
                          <span className="text-[11px] font-medium shrink-0" style={{ color: DIFFICULTY_COLOR[kw.difficulty] }}>{kw.difficulty}</span>
                          <span className="text-[10px] text-muted-foreground shrink-0 hidden sm:block">{kw.volume}</span>
                          <button
                            onClick={() => copyKw(kw.kw)}
                            className="opacity-0 group-hover:opacity-100 transition-opacity shrink-0"
                          >
                            {copiedKw === kw.kw
                              ? <Check size={13} className="text-emerald-500" />
                              : <Copy size={13} className="text-muted-foreground" />}
                          </button>
                        </motion.div>
                      )
                    })}
                  </motion.div>
                )}

                {/* Questions tab */}
                {activeTab === 'questions' && (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-2">
                    <p className="text-xs text-muted-foreground mb-3">
                      These "People Also Ask" questions are great for FAQ sections and featured snippets.
                    </p>
                    {generated.questions.map((q, i) => (
                      <motion.div
                        key={q.q}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.03 }}
                        className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-secondary/50 group transition-colors"
                      >
                        <span className="text-[11px] px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-500 font-medium shrink-0">PAA</span>
                        <span className="flex-1 text-sm">{q.q}</span>
                        <button onClick={() => copyKw(q.q)} className="opacity-0 group-hover:opacity-100 transition-opacity shrink-0">
                          {copiedKw === q.q ? <Check size={13} className="text-emerald-500" /> : <Copy size={13} className="text-muted-foreground" />}
                        </button>
                      </motion.div>
                    ))}
                  </motion.div>
                )}

                {/* LSI tab */}
                {activeTab === 'lsi' && (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                    <p className="text-xs text-muted-foreground mb-3">
                      Latent Semantic Indexing terms help Google understand your content's topic.
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {generated.lsi.map((term, i) => (
                        <motion.button
                          key={term}
                          initial={{ opacity: 0, scale: 0.9 }}
                          animate={{ opacity: 1, scale: 1 }}
                          transition={{ delay: i * 0.03 }}
                          onClick={() => copyKw(term)}
                          className="px-3 py-1.5 rounded-xl text-sm glass-card hover:border-primary/30 transition-all"
                        >
                          {copiedKw === term ? <Check size={12} className="inline mr-1 text-emerald-500" /> : null}
                          {term}
                        </motion.button>
                      ))}
                    </div>
                  </motion.div>
                )}
              </div>
            </GlassCard>

            {/* Export bar */}
            <div className="flex items-center justify-between gap-3 flex-wrap">
              <p className="text-xs text-muted-foreground">
                {generated.keywords.length + generated.questions.length + generated.lsi.length} total keywords generated
              </p>
              <div className="flex gap-2">
                <button
                  onClick={copyAll}
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl glass-card text-sm font-medium hover:border-primary/30 transition-all"
                >
                  <Copy size={13} />
                  Copy All
                </button>
                <button
                  onClick={exportAll}
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 transition-all"
                >
                  <Download size={13} />
                  Export TXT
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

